stages:
  verovio:
    foreach: ${samples}
    do:
      cmd: /home/kwon-young/prog/verovio/build/verovio -r /home/kwon-young/prog/verovio/data --xml-id-checksum
        -o data/${item}-verovio.svg data/${item}.musicxml
      deps:
      - data/${item}.musicxml
      outs:
      - data/${item}-verovio.svg
  svg2pl:
    foreach: ${samples}
    do:
      cmd: python svg2pl.py data/${item}-verovio.svg data/glyphnames.json data/${item}-verovio.pl
      deps:
      - data/${item}-verovio.svg
      - data/glyphnames.json
      - svg2pl.py
      outs:
      - data/${item}-verovio.pl
  musicReco:
    foreach: ${samples}
    do:
      cmd: swipl -t halt -s music.pl -g "mainReco('data/${item}-verovio.pl', 'settings/musicReco.txt', 'data/${item}-verovio.musicxml')."
      deps:
      - data/${item}-verovio.pl
      - ccx.pl
      - cond.pl
      - epf_geo.pl
      - epf.pl
      - geo.pl
      - music.pl
      - music_utils.pl
      - pitch_cond.pl
      - seg.pl
      - utils.pl
      - note.pl
      outs:
      - data/${item}-verovio.musicxml
  musicGen:
    foreach: ${samples}
    do:
      cmd: swipl -t halt -s music.pl -g "mainGen('data/${item}.musicxml', 'settings/musicGen.txt', 'data/${item}-music.pl')."
      deps:
      - data/${item}.musicxml
      - ccx.pl
      - cond.pl
      - epf_geo.pl
      - epf.pl
      - geo.pl
      - music.pl
      - music_utils.pl
      - pitch_cond.pl
      - seg.pl
      - utils.pl
      - note.pl
      outs:
      - data/${item}-music.pl
  diffXml:
    foreach: ${samples}
    do:
      cmd: swipl -t halt -s diffxml.pl -g "diffXml('data/${item}.musicxml', 'data/${item}-verovio.musicxml')."
      deps:
      - data/${item}.musicxml
      - data/${item}-verovio.musicxml
      - diffxml.pl
