stages:
  verovio:
    cmd: /home/kwon-young/prog/verovio/build/verovio -r /home/kwon-young/prog/verovio/data
      -o data/1-verovio.svg data/1.musicxml
    deps:
    - data/1.musicxml
    outs:
    - data/1-verovio.svg
  svg2pl:
    cmd: python svg2pl.py data/1-verovio.svg data/glyphnames.json data/1-verovio.pl
    deps:
    - data/1-verovio.svg
    - data/glyphnames.json
    - svg2pl.py
    outs:
    - data/1-verovio.pl
